version: "3"
services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    network_mode: "host"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    restart: unless-stopped
    network_mode: "host"
    environment:
      - discovery.type=single-node
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - http.port=9200

  api-gateway:
    image: api-gateway-docker
    container_name: api-gateway-docker
    restart: unless-stopped
    network_mode: "host"

  user-management:
    image: user-management-docker
    container_name: user-management-docker
    restart: unless-stopped
    network_mode: "host"

  notification:
    image: notification-docker
    container_name: notification-docker
    depends_on:
      - rabbit
    restart: unless-stopped
    network_mode: "host"

  video:
    image: video-docker
    container_name: video-docker
    depends_on:
      - rabbit
      - elasticsearch
    restart: unless-stopped
    network_mode: "host"

  frontend:
    image: frontend-docker
    container_name: frontend-docker
    restart: unless-stopped
    network_mode: "host"
